### ISSUE TITLE
Signing Certificate in schema?

### ISSUE THREAD

**Issue by chris2286266** [ehn-digital-green-development/ehn-dgc-schema#1]
Why is the Signing Certificate in DGC.schema.json?

    "dsc": {
      "description": "Document Signing Certificate: 8 bytes",
      "$ref": "https://ec.europa.eu/dgc/DGC.Types.schema.json#/$defs/dsc"
    },

shouldn't it be the "Certificate Identifier"?

    "certificate_id": {
      "description": "Certificate Identifier",
      "type": "string",
      "$comment": "SemanticSG: check spec for Cert ID: eHN Recovery pdf referred to Vacc UVCI for this field, so they _may_ all be in the same format as UVCI - or not?",
      "unique": true
    }

**Comment by martin-lindstrom** [comment]
It is the key identifier. See 3.3.3 of https://github.com/ehn-digital-green-development/hcert-spec/blob/main/hcert_spec.md.

Right?

**Comment by asitplus-pteufl** [comment]
confused... why is the KID in the schema? This is part of the CWT?

**Comment by jschlyter** [comment]
@gabywh do you if this is the KID? if so, we can just drop it as it is already in the CWT header.

**Comment by dirkx** [comment]
Agreed - no reason to have this in there twice &  @kruzikh
