### ISSUE TITLE
Use schema 2020-12?

### ISSUE THREAD

**Issue by jschlyter** [ehn-digital-green-development/ehn-dgc-schema#13]
I suggest that we use JSON schema 2020-12. If people need to use earlier versions for code generation, they can filter and downgrade, but the normative version should be a non-draft-version IMHO.

**Comment by jschlyter** [comment]
@martin-lindstrom hade some good input on this

**Comment by martin-lindstrom** [comment]
I haven't experienced any problems generating code from 2020-12 using for example the jsonschema2pojo-maven-plugin Maven plugin. 

Is there anyone that has any objections of changing to JSON schema 2020-12?

**Comment by jschlyter** [comment]
@dirkx any thoughts? We used 2020-12 in the "old" repo and I have not seen the justifications for the change to draft7.

**Comment by dirkx** [comment]
No opinion! Fine with me either way.

**Comment by martin-lindstrom** [comment]
Let's go with 2020-12!
