### ISSUE TITLE
given name needs to be come optional

### ISSUE THREAD

**Issue by dirkx** [ehn-digital-green-development/ehn-dgc-schema#14]
We probably need to drop the need to have both a GN and an FM; e.g. with an arab name; eg; this poet/physisisct you'd get:

 "nam": {
     "fnt": "ابو بكر محمد بن زكريا الرازي",
     "_fn": "ABU<BAKR<MOHAMMED<IBN<ZAKARIA<AL<RAZI",
  },

Then there is neither a given name or a first name. So this is what you see on a passport - no '<<' in sight. More examples  in the ICAO spec or in https://www.icao.int/Meetings/AMC/MRTD-SEMINAR-2011-DOHA/Documents/6_Ellis.pdf.

As we cannot use the "full stop" convention in the _gn (as the full stop would be dropped) - I suggest dropping the required value and documenting primary name use for this field.

**Comment by jschlyter** [comment]
Good
