### ISSUE TITLE
Where is the "sub" ?

### ISSUE THREAD

**Issue by rho-sk** [ehn-digital-green-development/ehn-dgc-schema#21]
Where do these change requests come from?
For the third time during the week, I am fundamentally reworking the api, due to these changes ....
What is the significance that at the moment the "sub" has completely disappeared from the scheme compared to the previous version?
https://github.com/ehn-digital-green-development/hcert-schema/eu_dgc_v1
Will it be added yet?

**Comment by jschlyter** [comment]
I've suggested in #10 that they are renamed back to it's previous names and objects. Please comment in that issue.
