### ISSUE TITLE
Schema $Id

### ISSUE THREAD

**Issue by jschlyter** [ehn-digital-green-development/ehn-dgc-schema#25]
We need to define a stables identifier (`$id`) for the schema. Preferably, it should be possible to retrieve the (combined) schema using the URI used as `$id`.

**Comment by gabywh** [comment]
Yes - waiting on a stable base address from eHealthNetwork deployment -> issue raised last Friday

**Comment by jschlyter** [comment]
@dirkx, please see if we get get a redirect in place so that `$Id/valuesets/XXX` are redirected (302) to `https://raw.githubusercontent.com/ehn-digital-green-development/ehn-dgc-schema/main/valuesets/XXX`. Perhaps the same could be used for the entire `$Id` namespace?

**Comment by dirkx** [comment]
So we can do two things 

-	We wait for T-Systems/SAP to dicuss this with DG-Connect and then push something operational at their facility with the first versions of the DGCG.

	Will take 3+ weeks most likely.

-	Quick 'hack' that maps id.uvci.eu -> raw.github.io/.......

	And we prefix it our URLS with http(s)://id.uvci.eu/

	And we later had over control of the URL to the LUX team that runs the DGCG.

-	As above - but we quickly register some other name like 'dgs-schemas.com' or something.

**Comment by jschlyter** [comment]
I'd go with `id.uvci.eu`

**Comment by dirkx** [comment]
The URL https://id.uvci.eu/<somthing> no points to anyt something in MAIN.
The URL https://id.uvci.eu/v1/<somthing> no points to anyt something in the branch v1 (which we do not yet have)
The URL https://id.uvci.eu/next/<somthing> no points to anyt something in the branch 'next'

If this works - will arrange /work with T-Systems.

**Comment by jschlyter** [comment]
Very good.

**Comment by jschlyter** [comment]
Can we close this @dirkx?
