### ISSUE TITLE
Use of value set updates schema for each added vaccine

### ISSUE THREAD

**Issue by sondaica** [ehn-digital-green-development/ehn-dgc-schema#26]
Should the schema be typed with value sets for changing information, ie vaccine?
According to Article 5 in the regulation 2021/0068 it should be possible to provide a vaccination certificate containing vaccine that has been  authorised by a competent authority of a Member State (MS). That will demand a new version of the schema when ONE MS authorize a new vaccine. But the other MS may only accept it in validation. But to be able to read the data all MS needs to update the validation when one MS authorize a new vaccine. Therefore its more safe to not use value sets in schema. Better to have them accessable in one place so that verifiers can use them instead. And more cost effective also.

**Comment by martin-lindstrom** [comment]
Yes. This is just one example why using enums in a schema that is most likely need to be updated pretty regularly isn't the best idea.

IMHO we really need to focus on the development/deployment on services that will rely on the schema. Let's supply the value sets in separate JSON-files outside of the schema. (As already provided in this repo in the Lookup-tables directory).

**Comment by jschlyter** [comment]
PR filed as #27. I suspect @gabywh may want to limit the maximum length and/or use a dedicated type.

**Comment by gabywh** [comment]
> PR filed as #27. I suspect @gabywh may want to limit the maximum length and/or use a dedicated type.

Yes: use dedicated type -> length thus implicitly limited by the items in the value set.

**Comment by jschlyter** [comment]
Issue resolved, still waiting on stable identifier though (handled via #25)
