### ISSUE TITLE
Array minItems = 1?

### ISSUE THREAD

**Issue by yspreen** [ehn-digital-green-development/ehn-dgc-schema#29]
Why should every cert include minimum one of each for:

- Vaccination Group
- Test Group
- Recovery Group

**Comment by dirkx** [comment]
Are you sure - if I feed them through the validator I get the expected {0,*} sort of behaviour ?

**Comment by jschlyter** [comment]
If you include any of then, they must not be empty. You can still emit them.

**Comment by yspreen** [comment]
I'm running with the first code from https://dgc.a-sit.at/ehn/testsuite

In the first field it says
```
{ "ver": "1.0.0", "nam": { "fn": "Musterfrau-G\u00f6\u00dfinger", "gn": "Gabriele", "fnt": "MUSTERFRAU<GOESSINGER", "gnt": "GABRIELE" }, "dob": "1998-02-26", "v": [ { "tg": "840539006", "vp": "1119305005", "mp": "EU\/1\/20\/1528", "ma": "ORG-100030215", "dn": 1, "sd": 2, "dt": "2021-02-18", "co": "AT", "is": "BMGSPK Austria", "ci": "ATOZQWGY3IOJUXGYTBOVWWC3TO" } ] }
```
But in the actual payload, the body is
```
"{\"-260\": {\"1\": {\"dob\": \"1998-02-26\", \"t\": [], \"r\": [], \"v\": [{\"vp\": \"1119305005\", \"sd\": 2, \"dt\": \"2021-02-18\", \"dn\": 1, \"co\": \"AT\", \"tg\": \"840539006\", \"mp\": \"EU/1/20/1528\", \"is\": \"BMGSPK Austria\", \"ci\": \"ATOZQWGY3IOJUXGYTBOVWWC3TO\", \"ma\": \"ORG-100030215\"}], \"nam\": {\"fnt\": \"MUSTERFRAU<GOESSINGER\", \"gnt\": \"GABRIELE\", \"fn\": \"Musterfrau-Gößinger\", \"gn\": \"Gabriele\"}, \"ver\": \"1.0.0\"}}, \"4\": 1651003677, \"6\": 1619467677, \"1\": \"AT\"}"	
```

Including empty r and t arrays. This trips up my validation. Might be a symptom of a bigger problem... Maybe just remove the minItems constraint?

**Comment by asitplus-pteufl** [comment]
@yspreen we will check this (the service you are referring to is the demo of the Austrian implementation)

**Comment by nodh** [comment]
@yspreen Thanks for observing, I've fixed it on the published service, please try again.
We had to set https://joelittlejohn.github.io/jsonschema2pojo/site/1.1.1/generate-mojo.html#initializeCollections to `true` to prevent empty arrays from being created in the data classes generated from the schema.

**Comment by jschlyter** [comment]
Resolved
