### ISSUE TITLE
Repository purpose

### ISSUE THREAD

**Issue by jschlyter** [ehn-digital-green-development/ehn-dgc-schema#3]
It seems the relationship between this repo and https://github.com/ehn-digital-green-development/hcert-schema needs clarification. More specifically, it needs to be justified where the schemas are not compatible.

**Comment by martin-lindstrom** [comment]
Great work on the value sets, but I also ask myself why a new repository is needed.

**Comment by martin-lindstrom** [comment]
Ping @gabywh Should we focus on this repo instead of hcert-schema?

**Comment by martin-lindstrom** [comment]
This has been resolved. The old schema repo has been retired.
