### ISSUE TITLE
Duplicate MAH

### ISSUE THREAD

**Issue by nodh** [ehn-digital-green-development/ehn-dgc-schema#32]
It seems, that `ORG-100020693` is included twice in the list of `vaccine-mah-manf`: https://github.com/ehn-digital-green-development/ehn-dgc-schema/blob/main/DGC-all-schemas-combined.json#L343 and directly after that.

**Comment by jschlyter** [comment]
Please check https://github.com/ehn-digital-green-development/ehn-dgc-schema/tree/next
