### ISSUE TITLE
Remove non-supported examples

### ISSUE THREAD

**Issue by kruzikh** [ehn-digital-green-development/ehn-dgc-schema#35]
@Gaby, I think that we should remove examples that are not correct according to the latest agreement: there will be just one dataset in a QR code.

**Comment by gaby** [comment]
@kruzikh You tagged the wrong person. :-)

@gabywh

**Comment by gabywh** [comment]
Once again this becomes a question of interplay between the DGC schema as transport mechanism and the application of business rules: I'm trying to keep these two concerns separate.

For now at least, nothing against "parking" the examples elsewhere that do not conform to the currently proposed legislation

**Comment by asitplus-pteufl** [comment]
@gabywh a question related to tests and defined behavior of validation apps, our view on the validation chain:

- check QR code structure/signatures/CBOR/COSE/Trust etc.
- then we finally have the hcert payload, this would be validated against the schema, to check whether it is a correct dgc.
- but, there seems to be an additional level now: a GDC could be perfectly valid according to the schema, but still be invalid (e.g. if multiple DGCs are contained). are there any other things you are aware of, where the schema would be correct but the DGC would still be invalid?
- of course after these checks national checks would still apply (validity times, vaccine acceptance)

we are setting up our test-case set (as here https://docs.google.com/document/d/14BvE_rqNkEqqe9RkdsWXbcUbMo9O4ax6a1VzDOAxP30/edit) and trying to collect all cases/corner cases.

**Comment by kruzikh** [comment]
> @kruzikh You tagged the wrong person. :-)
> 
> @gabywh

and who is the right one?

**Comment by gaby** [comment]
@gabywh is the right one :-)

**Comment by kruzikh** [comment]
@asitplus-pteufl  contrived-all-options.json should be removed as it confuses implementers. Currently one QR code should include only one certificate - according to the latest agreement. @gabywh @daniel?

**Comment by jschlyter** [comment]
Fixed in 7e981f9809a57d4db421f610d1ec3dc551b08b1b
