### ISSUE TITLE
Luhn mod N algorithm for checksum in UVCI

### ISSUE THREAD

**Issue by martin-lindstrom** [ehn-digital-green-development/ehn-dgc-schema#38]
Annex 2 in the [eHN Vacc Interop spec](https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf) specifies that the UCVI should have a checksum suffix according to the Luhn mod N-algorithm.

However, for interoperability, we need to be clear of the order of the allowed character set (A-Z 0-9 and '/', '#' and ':'). Each character needs to have code-point, and the spec isn't clear here. Should we read the following text:

> Charset: Only uppercase US-ASCII alpha numerical characters (‘A’ to ‘Z’, ‘0’ to ’9’) are allowed; with additional special characters for separation from RFC39865, namely {'/','#',':'};

and understand that the order should be: `ABCDEF....XYZ0123456789/#:`

Or should use Ascii-ordering?

**Comment by martin-lindstrom** [comment]
I guess that tthe `#` character should be left out from the Luhn-algorithm since it is only allowed to be used as a delimiter for the Luhn control char.

**Comment by gabywh** [comment]
More than that: in medical data, different delimiters are used as standard: ' ^ ' and ' | ' being the most standard and most common. These need to be included.

Codepoints should indeed be defined for Luhn-mod-N and I think the charset description is an attempt at that.
So I would see explicitly:

```ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/^|```

[eHN Vacc Interop spec](https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf), Annex 2:
 * Option 1 and Option 3 both explicitly require '/' as a field separator
 * Option 2 explicitly disallows it

(Note that the example given in https://github.com/ehn-digital-green-development/ehn-dgc-schema/issues/15#issuecomment-826711071 does NOT conform to the issued guidelines in Annex 2 as the example uses ' : ' explicilty as the field separator and is also in the regex pattern, but the eHN guidelines explicitly state that  '/' is the separator)

**Comment by martin-lindstrom** [comment]
> More than that: in medical data, different delimiters are used as standard: ' ^ ' and ' | ' being the most standard and most common. These need to be included.
> 
> Codepoints should indeed be defined for Luhn-mod-N and I think the charset description is an attempt at that.
> So I would see explicitly:
> 
> `ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/^|`

I don't understand how we ever will achieve interoperability if the specifications aren't clear and consise. So you mean that we shouldn't use what stated in annex 2?
> 
> [eHN Vacc Interop spec](https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf), Annex 2:
> 
> * Option 1 and Option 3 both explicitly require '/' as a field separator
> * Option 2 explicitly disallows it

No. Option 2 states: "
_The opaque unique string should consist of alphanumeric characters exclusively; no other characters (e.g. “/”) are allowed._"

But it doesn't explicitly state that '/' should be used as a delimitter. 

> 
> (Note that the example given in [#15 (comment)](https://github.com/ehn-digital-green-development/ehn-dgc-schema/issues/15#issuecomment-826711071) does NOT conform to the issued guidelines in Annex 2 as the example uses ' : ' explicilty as the field separator and is also in the regex pattern, but the eHN guidelines explicitly state that '/' is the separator)

Actually, what option 1 and 3 says is that '/' should be used as a delimitter for the blocks: issuing entity, (vaccine) and opaque unique string. It doesn't specify the delimitter for version and country.

So. The spec needs to be updated.

**Comment by dirkx** [comment]
> (Note that the example given in #15 (comment) <https://github.com/ehn-digital-green-development/ehn-dgc-schema/issues/15#issuecomment-826711071> does NOT conform to the issued guidelines in Annex 2 as the example uses ' : ' explicilty as the field separator and is also in the regex pattern, but the eHN guidelines explicitly state that '/' is the separator)
> 
> 
Ok - so my _intention_ was that the colons would separate between the colours in a URI fashion. And within the colours (i.e. green) we'd use a URI path spec separator. To stay close to the spirit of the URI definition. So 

       01:AR:<opaque with / as needed>

what exactly do we need to change in the document to fix this ? As I read it as pertaining to the green bits (which was what we intended).

**Comment by gabywh** [comment]
> > * Option 2 explicitly disallows it
> 
> No. Option 2 states: "
> _The opaque unique string should consist of alphanumeric characters exclusively; no other characters (e.g. “/”) are allowed._"
> 
> But it doesn't explicitly state that '/' should be used as a delimitter.
> 

Annex 2 explicitly excludes it - as you quote:
> no other characters (e.g. “/”) are allowed

**Comment by martin-lindstrom** [comment]
Yes. No other characters are allowed in the actual opaque string. But there is nothing to delimit in opaque string.

**Comment by gabywh** [comment]
>what exactly do we need to change in the document to fix this ? 
1. fully-defined codepoint set for UVCI
1. would be good to have a clear choice for Option 1 or 2 or 3. From internal discussions, SemanticSG had a preference for Option 3.
1. re-issue either a corrigenda or new doc - I suspect corrigenda? But I'll leave that to the process people to decide

**Comment by dirkx** [comment]
> The opaque unique string should consist of alphanumeric characters exclusively; no other characters (e.g. “/”) are allowed."
> 
> But it doesn't explicitly state that '/' should be used as a delimitter.
> 
Ok - so we need to clarify that this refers to the opaque string. (That is how it is intended, and that is how I read it).
> Annex 2 explicitly excludes it - as you quote:
> 
> no other characters (e.g. “/”) are allowed
> 
> 
Right - so we need to clarify that this refers to the green section.  (That is how it is intended, and that is how I read it - but it is clearly not clear enough).

Will you make a pass ?

**Comment by dirkx** [comment]
On 29 Apr 2021, at 09:35, Gaby Whitehead ***@***.***> wrote:
> what exactly do we need to change in the document to fix this ?
> 
> fully-defined codepoint set for UVCI
> would be good to have a clear choice for Option 1 or 2 or 3. From internal discussions, SemanticSG had a preference for Option 3.
> re-issue either a corrigenda or new doc - I suspect corrigenda? But I'll leave that to the process people to decide

I'd go back to the original version which was stripped. That had exact code points and a whole lot more detail in it.

**Comment by gabywh** [comment]
> Actually, what option 1 and 3 says is that '/' should be used as a delimitter for the blocks: issuing entity, (vaccine) and opaque unique string. It doesn't specify the delimitter for version and country.
> 

Indeed, those are missing in the doc but present in example https://github.com/ehn-digital-green-development/ehn-dgc-schema/issues/15

> So. The spec needs to be updated.

Agree.

**Comment by martin-lindstrom** [comment]
@dirkx Could you post an example of how a dutch ID would look like (including the Luhn control char)?

**Comment by gabywh** [comment]
some cert examples in: https://github.com/ehn-digital-green-development/ehn-dgc-schema/tree/main/examples

**Comment by gabywh** [comment]
Will close this one as we now just need the charset defined for Luhn-Mod-N, as per #45
