### ISSUE TITLE
Scheme used - https://json-schema.org/draft/2020-12/schema

### ISSUE THREAD

**Issue by PeterEbraert** [ehn-digital-green-development/ehn-dgc-schema#39]
Hello all,

Don't know if this is the right place... but... I have some questions w.r.t. the European DGC GW:
- What will be the process for delivering our public keys to the European gateway? 
- Is there a swagger available of that API? 
- Can someone provide me with the specific endpoints and the process of getting connected?
- How can we determine which public key to use (from all available public keys of one country) when validating a scanned QR code?
Thanks,

Peter

**Comment by dirkx** [comment]
ad 1, 3) see https://ec.europa.eu/health/key_documents_en and specifically the documents of the 21st of April volume 2 and 1.
ad 2) make sure you raise this in the wednesday Pilot meetings or contact Steffen Schultze directly.
ad 4) take the KID; run through the list of DGCG provided DSCs - and valdiate against each that has an identical KID.  For some countries it may be easier to make a 'map' of just the KID and X,Y of the P256 every night for efficiency purposes (e.g. see the json example at https://github.com/ehn-digital-green-development/masterlist-cert-generator)

**Comment by PeterEbraert** [comment]
Thanks Dirkx

1,3 I'll recheck that doc.
2 I'll raise the question in the meeting.
Didn't see there was a KID. :-) Problem of topic 4 solved.

**Comment by dirkx** [comment]
Beware of the KID - it is just 8 bytes ! So you need to _scan_ !
