### ISSUE TITLE
Are we finished by tomorrow?

### ISSUE THREAD

**Issue by martin-lindstrom** [ehn-digital-green-development/ehn-dgc-schema#41]
During this monday's meeting on DGC pilot testing there were some people at T-systems that claimed that the schema published in the EU-docs were the one to use. (Gaby's first draft of what we are working on). That won't work.

I also heard that in tommorrow's meeting the schema should be finalized. Are we ready our work to 1.0.0?

**Comment by jschlyter** [comment]
https://github.com/ehn-digital-green-development/ehn-dgc-schema/milestones ;-)

**Comment by jschlyter** [comment]
Yes we are.
