### ISSUE TITLE
Missing fields in examples

### ISSUE THREAD

**Issue by jkiddo** [ehn-digital-green-development/ehn-dgc-schema#43]
It seems like the fully dressed example on https://github.com/ehn-digital-green-development/ehn-dgc-schema/blob/main/examples/contrived-all-options.json is missing the t.ma field

**Comment by jschlyter** [comment]
The example has been removed in upcoming release.

**Comment by jschlyter** [comment]
Closed via d3f772a992cd7aca666c85d2c83742ec5ed253a3
