### ISSUE TITLE
Define UVCI format

### ISSUE THREAD

**Issue by gabywh** [ehn-digital-green-development/ehn-dgc-schema#44]
[eHN vaccination interop guidelines](https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf) - Annex 2.
1. Option 1?
1. Option 2? 
1. Option 3?

**Comment by gabywh** [comment]
[eHN Vacc Interop guidelines](https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf), Annex 2

Option 3 to be used.

**Comment by dirkx** [comment]
On 29 Apr 2021, at 16:03, Gaby Whitehead ***@***.***> wrote:
> eHN Vacc Interop guidelines <https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf>, Annex 2
> 
> Option 3 to be used.
> 
> 
Eh - the intention of this paper is that a country can choose any of these 3 options.

**Comment by gabywh** [comment]
> Eh - the intention of this paper is that a country can choose any of these 3 options. So this is not an either or thing. And this was the way it was voted upon / accepted.

Long discussions both here and offline about this - field missing in UVCI spec if we support all 3 options and implementers prefer just one choice.

**Comment by jschlyter** [comment]
Will be resolved in #52
