### ISSUE TITLE
Define charset for Luhn-Mod-N algorithm

### ISSUE THREAD

**Issue by gabywh** [ehn-digital-green-development/ehn-dgc-schema#45]
https://github.com/ehn-digital-green-development/ehn-dgc-schema/issues/38#issuecomment-829008964

closes #38

**Comment by gabywh** [comment]
[eHN Vacc Interop guidelines](https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf), Annex 2

Option 3 to be used.

**Comment by gabywh** [comment]
@jschlyter regex pattern for schema?

**Comment by martin-lindstrom** [comment]
My vote is also on option 3, but we need to decide on the charset.

- The prefix I see in examples "urn:uvci:". I guess we add that after the Luhn-calculation?
- Luhn charset? `ABCDE...XYZ0123456789/:`

**Comment by dirkx** [comment]
I'll make an example with calcualtion- we had that in Konstantin vfirst vrsion of the document

**Comment by jschlyter** [comment]
The specs refers to RFC 3986, but the UVCI are not URIs?

**Comment by dirkx** [comment]
prefixing it with a sensible urn: or IRI style prefix would make it so. They would not/never be URLs though.

**Comment by gabywh** [comment]
Are we talking Luhn-Mod-N or Luhn-10 here?
Annex 2 in the [eHN Vacc Interop](https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf) states:

> This checksum should be the ISO-7812-1 (LUHN-10) summary of the entire UVCI in digital/wire transport format.

(@martin-lindstrom so I guess that answers your question about scope of the checksum)

**Comment by gabywh** [comment]
> Are we talking Luhn-Mod-N or Luhn-10 here?
> Annex 2 in the [eHN Vacc Interop](https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf) states:
> 
> > This checksum should be the ISO-7812-1 (LUHN-10) summary of the entire UVCI in digital/wire transport format.
> 

Luhn-Mod-N would make sense here, Luhn-10 not, and the footnote (7) also discusses Luhn-Mod-N, so is the Luhn-10 reference simply a small error? 

Luhn-10 is the only ISO spec I know of in this context and AFAIK Luhn-Mod-N was never ISO (maybe someone else knows better?), so I can understand the Luhn-10 reference from that perspective, but that makes the text confusing since it clearly states Luhn-10 should be used.

Suggest wording to be sth like:

 "Luhn-Mod-N algorithm shall  be used" and in footnote 7 explain that Luhn-Mod-N is a variant on the basic Luhn-Mod-10 as per ISO 7812-1
