### ISSUE TITLE
Minimum dataset in regulation

### ISSUE THREAD

**Issue by sondaica** [ehn-digital-green-development/ehn-dgc-schema#47]
According to the latest adopted text in the regulation the minimum dataset shall include

date of vaccination, indicating the date of each dose received and of the latest dose received;

https://www.europarl.europa.eu/doceo/document/TA-9-2021-0145_EN.html

**Comment by martin-lindstrom** [comment]
Introduce extra field in vaccination_entry that is an array of dates?

**Comment by sondaica** [comment]
How do we fulfill the regulation regarding the other information about the vaccine if they are of different kinds the two doses? It states that the information about the vaccine manufacturer and type should be part of the datasets. So the schema works and fulfills the regulation if you add both doses without schema update.

**Comment by jschlyter** [comment]
Or we can just keep the current schema and allow multiple vaccinations in a single array.

**Comment by chris2286266** [comment]
> Or we can just keep the current schema and allow multiple vaccinations in a single array.

Yes, that would be the best solution. 
The only remaining topic is the ID ... (unique, see previous discussions ...)

**Comment by chris2286266** [comment]
> 
> 
> How do we fulfill the regulation regarding the other information about the vaccine if they are of different kinds the two doses? It states that the information about the vaccine manufacturer and type should be part of the datasets. So the schema works and fulfills the regulation if you add both doses without schema update.

Yes, that would be the best solution. 
But the only remaining topic is the ID ... (unique, see previous discussions ...)

**Comment by PeterEbraert** [comment]
In BE, we are going for a solution in which we will create 2 separate certificate for a person who received two doses.
Each certificate will house ONLY the data of the concerned dose.

However, the second certificate will mention the fact that it is the second dose that was administered.
Seems compliant to both Json and https://www.europarl.europa.eu/doceo/document/TA-9-2021-0145_EN.html
That would make the management of corrections a lot easier. What do you guys think?

**Comment by jschlyter** [comment]
@PeterEbraert This would be most unfortunate - how would that work at in inspection point? And how does the person verifying know that he/she must scan multiple HCERTs?

The schema was design explicitly to allow for multiple vaccinations etc., just for this use case. E.g. someone would be vaccinated with vaccin A and for some reason followed by B, both _can_ go into the same DGC.

**Comment by gabywh** [comment]
@PeterEbraert nothing preventing you doing that, LU are doing the same. Is a valid legal option that is supported by the DGC Schema. As @jschlyter points out, this may not be the most user-friendly approach, which is why the DGC Schema is designed to also accomodate those Member States who wish to incorporate more than one certificate per QR code. So long as you are in the end compliant with EU regulation, the choice is yours. The DGC Schema supports all these use cases.

**Comment by thinkberg** [comment]
Actually, in DE we are going for a similar approach. In fact, the doctor administering the second dose should check that there has been a dose administered before and thus certifies the full vaccination. I am not a doctor, nor regulator, but it would be my interpretation that a 2/2 certificate actually means exactly that: fully vaccinated. It only gets complicated if a combination would be forbidden later on.

**Comment by gabywh** [comment]
> but it would be my interpretation that a 2/2 certificate actually means exactly that: fully vaccinated

Not necessarily - quite a few edge cases here. In any case, two different perspectives here: (i) medical, and (ii) regulatory - as per EU regs: the legal people can set that 2/2 "is equivalent to" fully vaccinated for the purposes of cross border travel. From a medical perspective, the only thing I can conclude from 2/2 is that 2 doses have been administered with a nominal total series dosage of 2, nothing more than that. I would need to do a lot more looking at other medical to make any medical claim about whether this means - from a medical perspective - person is fully vaccinated. This is why e.g. the HL7 model has a separate field called "status" which can be set to e.g. completed. Anyway, out-of-scope here: for our purposes for cross-border travel - 2/2 (or 1/1 etc) is deemed to be equivalent to "fully vaccinated".

**Comment by thinkberg** [comment]
I fully agree. However, from a practical point of view, we can assume lazy people.
