### ISSUE TITLE
Recovery certificates

### ISSUE THREAD

**Issue by PeterEbraert** [ehn-digital-green-development/ehn-dgc-schema#51]
What kind of data will you guys use to issue a recovery certificate?
We were thinking to only issue them for people who had a positive antibody test.
Should we consider to issue such certificates to people who had a positive PCR test (with a validity date N days after such a test)? 
What are the other countries doing wrt those BIZ rules?

**Comment by martin-lindstrom** [comment]
I suggest that you use the Slack-channel for questions that do not really concern the development of the schema.
