### ISSUE TITLE
Bug in DOB regex

### ISSUE THREAD

**Issue by agerlach-tsi** [ehn-digital-green-development/ehn-dgc-schema#53]
Hi,

why the regex check in the dob, which is already declared as format "date"?

https://github.com/ehn-digital-green-development/ehn-dgc-schema/blob/73178219592a1b351bf48a53012b6bcf0122c16c/DGC.schema.json#L31

Also, it does not allow 10 or 20 as a day.

**Comment by jschlyter** [comment]
The format is only to limit the century, so I suggest:

```
--- a/DGC.schema.json
+++ b/DGC.schema.json
@@ -29,7 +29,7 @@
       "description": "Date of Birth of the person addressed in the DGC. ISO 8601 date format restricted to range 1900-2099",
       "type": "string",
       "format": "date",
-      "pattern": "[19|20][0-9][0-9]-(0[1-9]|1[0-2])-([0-2][1-9]|3[0|1])",
+      "pattern": "[19|20]\\d{2}-\\d{2}-\\d{2}",
       "examples": [
         "1979-04-14"
       ]
```

**Comment by agerlach-tsi** [comment]
Then you should go for `(19|20)\\d{2}-\\d{2}-\\d{2}`, imho. Your suggestion `[19|20]` also validates 1200 correctly.

**Comment by jschlyter** [comment]
Thanks, fixed now.
