### ISSUE TITLE
test-results.json vs test-result.json

### ISSUE THREAD

**Issue by miguelzapaton** [ehn-digital-green-development/ehn-dgc-schema#71]
Dear DGC Schema Team,

During my JSON validation experiments I've found a little inconsistency: 

In the following JSON Schema:

https://github.com/ehn-digital-green-development/ehn-dgc-schema/blob/main/DGC.ValueSets.schema.json

test-result**s**.json is referenced:

```
    "test-result": {
      "description": "EU eHealthNetwork: Value Sets for Digital Green Certificates. version 1.0, 2021-04-16, section 2.9",
      "type": "string",
      "valueset-uri": "valuesets/test-results.json"
    },
```

However the file is called **test-result.json**

https://github.com/ehn-digital-green-development/ehn-dgc-schema/blob/main/valuesets/test-result.json

So I would propose either renaming the file or updating the reference.

Miguel

**Comment by jschlyter** [comment]
Fixed in next release
