### ISSUE TITLE
Why AGAIN THOSE CHANGES !!!!!

### ISSUE THREAD

**Issue by rho-sk** [ehn-digital-green-development/ehn-dgc-schema#86]

**Comment by ryanbnl** [comment]
Please bear in mind that this is a public forum. The entire world can see what you're posting here. We're all under a lot of pressure, and some of us will be releasing in a few days. I understand your feelings of frustration.. but you might want to re-read your issue and edit it appropriately :)

**Comment by rho-sk** [comment]
> Please bear in mind that this is a public forum. The entire world can see what you're posting here. We're all under a lot of pressure, and some of us will be releasing in a few days. I understand your feelings of frustration.. but you might want to re-read your issue and edit it appropriately :)

Also respect the fact that national solutions also have their deadlines.  Every change here is reflected almost automatically in dozens of other systems, where the situation is much more complex than just renaming a file.

**Comment by ryanbnl** [comment]
Of course, and you should absolutely feel free to air that view. That's what is great about living in liberal democracies. However I think you'll regret this when the pressure is over, and us developers should try to look out for each other :)

**Comment by rho-sk** [comment]
yes, things can be done in different ways, and they can be communicated in different ways, especially when the whole world can look at this.

**Comment by hinca** [comment]
> you might want to re-read your issue and edit it appropriately :)
![image](https://user-images.githubusercontent.com/9134444/120440664-11ffac80-c384-11eb-9247-4ba6a9907295.png)

Editing it is not necessarily enough for the embarrassing information to stay out of sight.  :)  Have a good day, folks.
